### PR TITLE
fix: make sure server recover after panic

### LINKED ISSUE #30: Make sure server recover after panic

### PR DESCRIPTION
**Pull request by maxlivinci**
resolves #30

---

1. Add a `panic` inside the `ValidateNode` function.

image

2. Trigger add node events.

image

3. Check logs

image

### CODE REVIEW

File: services/index/internal/controller/event/listeners.go [hunk 1]
```diff
@@ -28,6 +30,12 @@ func NewNodeHandler(nodeService service.NodesService) NodeHandler {
 
 func (handler *nodeHandler) Validated() error {
 	return event.NewNodeValidatedListener(nats.Client.Client(), QGROOP, func(msg *stan.Msg) {
+		defer func() {
+			if err := recover(); err != nil {
+				logger.Error(fmt.Sprintf("Panic occurred in nodeValidated handler: %v", err), errors.New("painc"))
```
Comment (geoffturk) [inline services/index/internal/controller/event/listeners.go:35]: Typo: panic

**Review by geoffturk — APPROVED** [review]
LGTM 🚀
